repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: requirements-txt-fixer
        name: Requirements
        types: [file]
        exclude_types: ["image"]
      - id: debug-statements
        name: Debugging
        language: python
        types: [file, python]
        exclude_types: ["image"]
      - id: trailing-whitespace
        name: Trailing Whitespace
        language: python
        types: [file]
        exclude_types: ["image", "markdown"]
      - id: end-of-file-fixer
        name: EOF Newlines
        language: python
        types: [file]
        exclude_types: ["image"]
      - id: check-yaml
        name: YAML Structure
        language: python
      - id: check-toml
        name: TOML Structure
      - id: check-merge-conflict
        name: Merge Conflicts
  - repo: https://github.com/odwyersoftware/brunette
    rev: 0.2.7
    hooks:
      - id: brunette
        args: [--safe, --quiet, --single-quotes, --line-length=100]
  - repo: https://github.com/astral-sh/ruff-pre-commit # replace `isort` and `flake8`
    rev: v0.0.282
    hooks:
      - id: ruff
        args: [--fix, --line-length=100, --exit-non-zero-on-fix]
ci:
  autofix_prs: true
  autofix_commit_msg: "ci: correct from checks."
